services:
  app: 
    build:
      context: . 
      dockerfile: Dockerfile 
      target: ${BUILD_TARGET:-base} # Defaults to 'base' if BUILD_TARGET is not set
    volumes:
      - .:/var/www/html 
    ports:
      - 8000:80 
    env_file:
      - .env # Load environment variables from .env file for the 'app' service
    depends_on:
      - db 
      - memcached-server
      - redis-server
    container_name: my-laravel-app # Assign a fixed name to the container

  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/var/www/html
    env_file:
      - .env.testing
    depends_on:
      - db
      - memcached-server
      - redis-server
    container_name: my-laravel-app-test

  db:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=${DB_DATABASE} 

  memcached-server: 
    image: memcached:1.6-alpine

  redis-server: 
    image: redis:6-alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db 
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db