<?php

namespace App\Http\Controllers\API;

use App\Models\Voucher as ModelsVoucher;
use App\Http\Resources\PaginationResource;
use App\Http\Controllers\API\BaseController;
use App\Http\Requests\VoucherRedeemRequest;
use App\Http\Requests\VoucherRequest;
use App\Models\CourseCategory;
use App\Models\UserCourseCategory;
use App\Models\UserCourse;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\RateLimiter;

class VoucherController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $voucher = new PaginationResource(ModelsVoucher::search($request)->with(['createdBy', 'courseCategory', 'redeemedBy'])->paginate($request->limit));
        return $this->ressSuccess([
            'message' => 'Successfully get Voucher',
            'data' => ['voucher' => $voucher]
        ]);
    }

    private function checkPrakerjaVoucher($voucher, $sequence)
    {
        $redeem_code = $voucher; // redeem code generated by system when user buy training
        $client_code = env('PRAKERJA_CLIENT_CODE', ''); // provided by Prakerja
        $timestamp = time(); // generate current timestamp
        $method = 'POST'; // API Method
        $endpoint = '/api/v1/integration/payment/redeem-code/status'; // API Redeem Status Endpoint

        $data = ['redeem_code' => $voucher, 'sequence' => $sequence];

        $input = $client_code . $timestamp . $method . $endpoint . json_encode($data); // create signature input
        $sign_key = env('PRAKERJA_CREDENTIAL', ''); // provided by Prakerja
        if (empty($sign_key)) {
            throw new Exception('PRAKERJA_CREDENTIAL is empty!');
        }
        $signature = hash_hmac('sha1', $input, $sign_key); // generate signature

        $headers = [
            'Content-Type: application/json',
            'client_code: ' . $client_code,
            'signature: ' . $signature,
            'timestamp: ' . $timestamp,
        ];
        $data = [
            'redeem_code' => $redeem_code,
            'sequence' => $sequence
        ];
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,            'https://api.prakerja.go.id' . $endpoint);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST,           1);
        curl_setopt($ch, CURLOPT_HTTPHEADER,     $headers);
        curl_setopt($ch, CURLOPT_POSTFIELDS,     json_encode($data));
        $result = curl_exec($ch);
        curl_close($ch);


        return $result;
    }

    private function generateURL($voucher, $sequence, $email, $redirect_uri)
    {
        $redeem_code = $voucher; // redeem code generated by system when user buy training

        $client_code = env('PRAKERJA_CLIENT_CODE', ''); // provided by Prakerja

        $timestamp = time(); // generate current timestamp
        $method = 'POST'; // API Method
        $endpoint = '/api/v1/integration/oauth/url-generate'; // API Redeem Status Endpoint

        $data = ['redeem_code' => $voucher, 'sequence' => $sequence, 'redirect_uri' => $redirect_uri, 'email' => $email];

        $input = $client_code . $timestamp . $method . $endpoint . json_encode($data); // create signature input

        $sign_key = env('PRAKERJA_CREDENTIAL', ''); // provided by Prakerja
        if (empty($sign_key)) {
            throw new Exception('PRAKERJA_CREDENTIAL is empty!');
        }
        $signature = hash_hmac('sha1', $input, $sign_key); // generate signature

        $headers = [
            'Content-Type: application/json',
            'client_code: ' . $client_code,
            'signature: ' . $signature,
            'timestamp: ' . $timestamp,
        ];
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,            'https://api.prakerja.go.id' . $endpoint);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST,           1);
        curl_setopt($ch, CURLOPT_HTTPHEADER,     $headers);
        curl_setopt($ch, CURLOPT_POSTFIELDS,     json_encode($data));
        $result = curl_exec($ch);
        curl_close($ch);

        $result_json = json_decode($result, true);
        return $result_json;
    }

    private function commitPrakerjaVoucher($voucher)
    {
        $client_code = 'startup-campus-0';
        $redeem_code = $voucher;
        $key = env('PRAKERJA_CREDENTIAL', '');
        $endpoint = '/api/v1/integration/payment/redeem-code/commit';
        $timestamp = time();
        $text = $client_code . $timestamp . 'POST' . $endpoint . '{"redeem_code":"' . $redeem_code . '"}';
        $signature = hash_hmac('sha1', $text, $key);

        $headers = [
            'Content-Type: application/json',
            'client_code: ' . $client_code,
            'signature: ' . $signature,
            'timestamp: ' . $timestamp,
        ];
        $data = [
            'redeem_code' => $redeem_code
        ];

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL,            'https://api.prakerja.go.id' . $endpoint);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST,           1);
        curl_setopt($ch, CURLOPT_HTTPHEADER,     $headers);
        curl_setopt($ch, CURLOPT_POSTFIELDS,     json_encode($data));
        $result = curl_exec($ch);
        curl_close($ch);

        $result_json = json_decode($result, true);
        return $result_json;
    }

    public function redeem(VoucherRedeemRequest $request)
    {
        # Prakerja voucher hit the Prakerja API for validation and redeem.
        $request->validated();
        $input = $request->toArray();
        $successCheckVoucherPrakerja = false;
        $voucher = $input['token'];
        $redirect_uri = $input['redirect_uri'];
        $sequence = $input['sequence'];

        $checkVoucherResponse = $this->checkPrakerjaVoucher($voucher, $sequence);
        // Log::info('this is check voucher -- ' . $checkVoucherResponse);

        $voucherData = json_decode($checkVoucherResponse, true);
        $success = $voucherData['success'];
        $message = $voucherData['message'];

        if ($success) {
            // Log::info('SUKSES -- ' . $checkVoucherResponse);
            $status = $voucherData['data']['status'];
            $attendance_status = $voucherData['data']['attendance_status'];
            $redeem_code = $voucherData['data']['redeem_code'];
            $courseCode = $voucherData['data']['course_code'];

            if ($sequence === 1) {
                if (strpos($redeem_code, 'PRAM') === 0) {

                    // Ambil semua UserCourseCategory dengan user_id yang sama
                    $userCourseCategories = UserCourseCategory::where('user_id', Auth::user()->id)->get();

                    foreach ($userCourseCategories as $userCourseCategory) {
                        if ($userCourseCategory->update(['redeem_code' => $redeem_code])) {
                            Log::info('Berhasil mengupdate redeem_code untuk user_course_category dengan id: ' . $userCourseCategory->id);
                        } else {
                            Log::error('Gagal mengupdate redeem_code untuk user_course_category dengan id: ' . $userCourseCategory->id);
                        }
                    }
                } else {
                    // Jika bukan kode PRAM, gunakan whereHas untuk memeriksa prakerja_course_id
                    $userCourseCategories = UserCourseCategory::whereHas('courseCategory', function ($query) use ($courseCode) {
                        $query->where('prakerja_course_id', $courseCode);
                    })
                        ->where('user_id', Auth::user()->id)
                        ->get();

                    // Log jumlah data yang diambil
                    Log::info('Jumlah UserCourseCategory dengan courseCode: ' . $userCourseCategories->count());

                    foreach ($userCourseCategories as $userCourseCategory) {
                        if ($userCourseCategory->update(['redeem_code' => $redeem_code])) {
                            Log::info('Berhasil mengupdate redeem_code untuk user_course_category dengan id: ' . $userCourseCategory->id);
                        } else {
                            Log::error('Gagal mengupdate redeem_code untuk user_course_category dengan id: ' . $userCourseCategory->id);
                        }
                    }
                }
            }
            
            if ($status === 1 || $status === 0) {
                if ($attendance_status === 1) {
                    // Log::info('Data <><><> ' . $voucherData);
                    return $this->ressSuccess([
                        'message' => 'User sudah menghadiri kursus.',
                        'data' => $voucherData['data']
                    ]);
                } else {
                    $successCheckVoucherPrakerja = true;
                }
            }
        } else {
            return $this->ressError([
                'message' => $message,
                'data' => $voucherData,
            ]);
        }

        // Jika $successCheckVoucherPrakerja bernilai true, lanjutkan ke tahapan berikutnya
        if ($successCheckVoucherPrakerja) {

            $email = Auth::user()->email;
            $response = $this->generateURL($voucher, $sequence, $email, $redirect_uri);
            $success = $response['success'];
            $message = $response['message'];

            if (!$success) {
                return $this->ressError([
                    'message' => $message,
                    'data' => $response,
                ]);
            } else {
                return $this->ressSuccess([
                    'message' => 'Kode Redeem berhasil ditukarkan!',
                    'data' => $response['data'],
                ]);
            }
        }

        return $this->ressSuccess([
            'message' => '',
            'data' => [],
        ]);
    }

    public function voucher(VoucherRedeemRequest $request)
    {
        # Rate limit: 10 requests per minute per IP
        if (!RateLimiter::attempt('voucher-redeem:' . $request->ip(), 10, function() {})) {
            return $this->ressError([
                'message' => 'Sistem sedang sibuk. Silakan coba lagi dalam beberapa saat.',
                'data' => []
            ]);
        }

        # Internal Startup Campus (in our database) voucher redeem
        $request->validated();
        $input = $request->toArray();

        $voucher = ModelsVoucher::where('token', $input['token'])->with('courseCategory')->first();

        if (!$voucher) {
            return $this->ressError([
                'message' => 'Voucher tidak ditemukan',
                'data' => []
            ]);
        }
        if ($voucher->is_redeemed) {
            return $this->ressError([
                'message' => 'Voucher sudah pernah ditukarkan!',
                'data' => []
            ]);
        }

        if ($voucher) { # Logic for internal voucher
            $courseCategoryId = $voucher->course_category_id;
            $courseCategoryName = $voucher->courseCategory->name;
        }

        $uCCExists = UserCourseCategory::where('course_category_id', $courseCategoryId)->where('user_id', Auth::user()->id)->first();
        if ($uCCExists) {
            return $this->ressError([
                'message' => 'Kamu sudah tergabung ke course ' . $courseCategoryName . '!',
                'data' => []
            ]);
        }

        # Redeem Course
        $voucher->update([
            'is_redeemed' => true,
            'redeemed_by' => Auth::user()->id,
        ]);

        # Enroll user
        $uCC = UserCourseCategory::create([
            'course_category_id' => $courseCategoryId,
            'user_id' => Auth::user()->id,
        ]);

        return $this->ressSuccess([
            'message' => 'Voucher berhasil ditukarkan! Kamu bisa mengakses course ' . $courseCategoryName . '.Selamat belajar!',
            'data' => [
                'voucher' => $voucher,
                'course_category_id' => $courseCategoryId,
                'user_course_category' => $uCC,
            ]
        ]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VoucherRequest $request)
    {
        $request->validated();
        $input = $request->toArray();

        $courseCategory = CourseCategory::find($input['course_category_id']);
        if (empty($courseCategory)) {
            return $this->ressError([
                'message' => 'Course Category not found!',
                'data' => []
            ]);
        }

        try {
            $voucher = ModelsVoucher::create($input);
            return $this->ressSuccess([
                'message' => 'Successfully create voucher',
                'data' => [
                    'voucher' => $voucher,
                ]
            ]);
        } catch (\Throwable $th) {
            Log::error($th);
            return $this->ressError([
                'message' => $th->getMessage(),
                'data' => []
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $voucher = ModelsVoucher::find($id);
        if (empty($voucher)) {
            return $this->ressError([
                'message' => 'Course Category not found!',
                'data' => []
            ]);
        }
        try {
            return $this->ressSuccess([
                'message' => 'Show Course Category',
                'data' => [
                    'voucher' => $voucher,
                ]
            ]);
        } catch (\Throwable $th) {
            Log::error($th);
            return $this->ressError([
                'message' => $th->getMessage(),
                'data' => []
            ]);
        }
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function update(VoucherRequest $request, $id)
    {
        $request->validated();
        $input = $request->toArray();
        $voucher = ModelsVoucher::find($id);
        if (empty($voucher)) {
            return $this->ressError([
                'message' => 'Data course category cannot find!',
                'data' => []
            ]);
        }

        try {
            $voucherUpdate = ModelsVoucher::updateOrCreate(['id' => $voucher->id], $input);
            return $this->ressSuccess([
                'message' => 'Successfully update Course Category',
                'data' => [
                    'voucher' => $voucherUpdate,
                ]
            ]);
        } catch (\Throwable $th) {
            Log::error($th);
            return $this->ressError([
                'message' => $th->getMessage(),
                'data' => []
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\voucher  $voucher
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $voucher = ModelsVoucher::find($id);
        if (empty($voucher)) {
            return $this->ressError([
                'message' => 'Cannot find data',
                'data' => []
            ]);
        }

        try {
            $voucher->delete();
            return $this->ressSuccess([
                'message' => 'Successfully delete voucher',
                'data' => []
            ]);
        } catch (\Throwable $th) {
            Log::error($th);
            return $this->ressError([
                'message' => $th->getMessage(),
                'data' => []
            ]);
        }
    }
}
